# Basic Anthropic Claude Configuration
# Usage: python -m src.main --config examples/configs/anthropic-basic.yaml

server:
  port: 3000
  host: "0.0.0.0"
  workers: 1

llm:
  base_url: "https://api.anthropic.com"
  type: "anthropic"
  # api_key: "${ANTHROPIC_API_KEY}"  # Optional - uncomment if you want API key injection
  timeout: 30
  max_retries: 3

interceptors:
  # Cylestio smart session management - must be first!
  - type: "cylestio_session"
    enabled: true
    config:
      max_sessions: 10000  # Maximum number of sessions to track
      session_ttl_seconds: 3600  # Session timeout in seconds
      enable_fuzzy_matching: true  # Smart session continuation
      similarity_threshold: 0.85  # Fuzzy matching threshold (0-1)
      track_session_metrics: true  # Enable session metrics
      include_client_info: true  # Include client IP, user-agent etc
      log_session_events: true  # Log session start/end events

  - type: "printer"
    enabled: true
    config:
      log_requests: true
      log_responses: true
      log_body: true  # Required to count messages
      show_sessions: true
      show_llm_calls: true
      show_tools: true

  # Message logger for LLM conversations
  - type: "message_logger"
    enabled: true
    config:
      directory: "./message_logs"
      filename: "message_log.jsonl"
      include_system_prompts: true
      include_metadata: true
      buffer_size: 10  # Buffer 10 messages before writing to disk

      

logging:
  level: "INFO"
  format: "text"

# Session management is now handled by the cylestio_session interceptor above