# Basic Anthropic Claude Configuration
# Usage: python -m src.main --config examples/configs/anthropic-basic.yaml

server:
  port: 3000
  host: "0.0.0.0"
  workers: 1

llm:
  base_url: "https://api.anthropic.com"
  type: "anthropic"
  # api_key: "${ANTHROPIC_API_KEY}"  # Optional - uncomment if you want API key injection
  timeout: 30
  max_retries: 3

interceptors:
  - type: "printer"
    enabled: true
    config:
      log_requests: true
      log_responses: true
      log_body: true  # Required to count messages
      show_sessions: true
      show_llm_calls: true
      show_tools: true

  # Cylestio trace interceptor
  - type: "cylestio_trace"
    enabled: true
    config:
      api_url: "http://localhost:8000"
      access_key: "${CYLESTIO_ACCESS_KEY}"  # Set this environment variable
      timeout: 10

  # Event recorder - saves raw events to disk per session
  - type: "event_recorder"
    enabled: true
    config:
      output_dir: "./event_logs"        # Directory to save event files
      file_format: "jsonl"              # "json" or "jsonl" format
      pretty_print: false               # Pretty-print JSON (only for "json" format)
      include_metadata: true            # Include file metadata

logging:
  level: "INFO"
  format: "text"

# Session management configuration (built into core platform)
session:
  enabled: true
  max_sessions: 10000  # Maximum number of sessions to track in memory
  session_ttl_seconds: 3600  # Sessions expire after 1 hour of inactivity
