# Basic Anthropic Claude Configuration
# Usage: python -m src.main --config examples/configs/anthropic-basic.yaml

server:
  port: 3000
  host: "0.0.0.0"
  workers: 1

llm:
  base_url: "https://api.anthropic.com"
  type: "anthropic"
  # api_key: "${ANTHROPIC_API_KEY}"  # Optional - uncomment if you want API key injection
  timeout: 30
  max_retries: 3

interceptors:
  - type: "printer"
    enabled: true
    config:
      log_requests: true
      log_responses: true
      log_body: true  # Required to count messages
      show_sessions: true
      show_llm_calls: true
      show_tools: true

  # Message logger for LLM conversations
  - type: "message_logger"
    enabled: true
    config:
      directory: "./message_logs"
      filename: "message_log.jsonl"
      include_system_prompts: true
      include_metadata: true
      buffer_size: 1  # Buffer 1 message before writing to disk (for testing)

      

logging:
  level: "INFO"
  format: "text"

# Session management configuration (built into core platform)
session:
  enabled: true
  max_sessions: 10000  # Maximum number of sessions to track in memory
  session_ttl_seconds: 3600  # Sessions expire after 1 hour of inactivity
  enable_fuzzy_matching: true  # Try to match continued conversations
  similarity_threshold: 0.85  # Similarity score needed for fuzzy matching (0-1)
  max_messages_for_new_session: 3  # Conversations with <= 3 messages may be new sessions
  reset_phrases:  # Phrases that trigger a new session
    - "start over"
    - "new conversation"
    - "reset"
    - "clear"
    - "begin again"
    - "fresh start"
    - "new session"
    - "new chat"