# Basic Anthropic Claude Configuration
# Usage: python -m src.main --config examples/configs/anthropic-basic.yaml

server:
  port: 3000
  host: "0.0.0.0"
  workers: 1

llm:
  base_url: "https://api.anthropic.com"
  type: "anthropic"
  # api_key: "${ANTHROPIC_API_KEY}"  # Optional - uncomment if you want API key injection
  timeout: 30
  max_retries: 3

middlewares:
  - type: "printer"
    enabled: true
    config:
      log_requests: true
      log_responses: true
      log_body: false

logging:
  level: "INFO"
  format: "text"