# Basic Anthropic Claude Configuration
# Usage: python -m src.main --config examples/configs/anthropic-basic.yaml

server:
  port: 3000
  host: "0.0.0.0"
  workers: 1

llm:
  base_url: "https://api.anthropic.com"
  type: "anthropic"

interceptors:
  # - type: "printer"
  #   enabled: true
  #   config:
  #     log_requests: true
  #     log_responses: true
  #     log_body: true  # Required to count messages
  #     show_sessions: true
  #     show_llm_calls: true
  #     show_tools: true

  # # Cylestio trace interceptor
  # - type: "cylestio_trace"
  #   enabled: true
  #   config:
  #     api_url: "http://localhost:8000"

  # Event recorder - saves raw events to disk per session
  # - type: "event_recorder"
  #   enabled: true
  #   config:
  #     output_dir: "./event_logs"        # Directory to save event files
  #     file_format: "jsonl"              # "json" or "jsonl" format
  #     pretty_print: false               # Pretty-print JSON (only for "json" format)
  #     include_metadata: true            # Include file metadata

  # Live trace dashboard for real-time debugging
  - type: live_trace
    enabled: true
    config:
      server_port: 8080
      auto_open_browser: true
      max_events: 10000
      retention_minutes: 30
      refresh_interval: 2

  # # HTTP recorder - saves raw HTTP traffic for replay testing
  # - type: "http_recorder"
  #   enabled: true
  #   config:
  #     output_dir: "./http_recordings"   # Directory to save HTTP recordings
  #     max_events_per_file: 50           # Rotate to new file after N events
  #     include_headers: true             # Include HTTP headers
  #     include_timing: true              # Include timing information
  #     max_body_size_mb: 50              # Max body size to record
