# Development Configuration with Debug Logging
# Usage: python -m src.main --config examples/configs/development.yaml

server:
  port: 3001
  host: "127.0.0.1"  # Local only for development
  workers: 1

llm:
  base_url: "https://api.openai.com"
  type: "openai"
  api_key: "${OPENAI_API_KEY}"
  timeout: 30
  max_retries: 1  # Fail fast in development

interceptors:
      
  # Verbose printer middleware
  - type: "printer"
    enabled: true
    config:
      log_requests: true
      log_responses: true
      log_body: true  # Full body logging for debugging

logging:
  level: "DEBUG"  # Verbose logging
  format: "text"  # Human-readable format
  file: null  # Console only