# OpenAI Configuration with Event Recording
# Usage: python -m src.main --config examples/configs/openai-with-event-recording.yaml

server:
  port: 3000
  host: "0.0.0.0"
  workers: 1

llm:
  base_url: "https://api.openai.com/v1"
  type: "openai"
  timeout: 30
  max_retries: 3

interceptors:
  - type: "printer"
    enabled: true
    config:
      log_requests: true
      log_responses: true
      log_body: false

  # Event recorder - saves raw events to disk per session
  - type: "event_recorder"
    enabled: true
    config:
      output_dir: "./event_logs"        # Directory to save event files
      file_format: "jsonl"              # "json" or "jsonl" format
      pretty_print: false               # Pretty-print JSON (only for "json" format)
      include_metadata: true            # Include file metadata
      
  # Cylestio trace interceptor
  - type: "cylestio_trace"
    enabled: true
    config:
      api_url: "http://localhost:8000"
      access_key: "${CYLESTIO_ACCESS_KEY}"  # Set this environment variable
      timeout: 10
      
logging:
  level: "INFO"
  format: "text"
