# Basic OpenAI Configuration
# Usage: python -m src.main --config examples/configs/openai-basic.yaml

server:
  port: 3000
  host: "0.0.0.0"
  workers: 1

llm:
  base_url: "https://api.openai.com"
  type: "openai"
  api_key: "${OPENAI_API_KEY}"  # Set via environment variable
  timeout: 30
  max_retries: 3

interceptors:
  - type: "printer"
    enabled: true
    config:
      log_requests: true
      log_responses: true
      log_body: false

logging:
  level: "INFO"
  format: "text"